[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
chrono = "0.4.23"
bson = { version = "2.5.0", features = ["chrono-0_4"] }